Map<String, Map<String, List<String>>> inspirationalQuotes = {
  "he": {
    "male": [
      "מה יעזור לי כעת, גם צעדים קטנים זאת התקדמות",
      "יש בי חוזקות",
      "בעבר כבר התמודדתי עם אתגרים",
      "מצב הרוח משתנה כמו מזג האוויר שאינו קבוע",
      "רגשות חולפים ומשתנים",
      "אני מסוגל",
      "יש לי כוחות",
      "אני לומד להירגע",
      "אחרי הירידות באות העליות",
      "זה בסדר לבכות",
      "תודה על היש",
      "קח רגע לחייך",
      "לזכור לנשום",
      "שגרה מייצרת יציבות",
      "תנועה מוציאה מיקפאון",
      "זה בסדר לבקש עזרה",
      "זה בסדר לא להיות בסדר",
      "שמור על הקצב שנכון לך",
      "מה נותן לך כוח להמשיך?"
    ],
    "female": [
      "מה יעזור לי כעת, גם צעדים קטנים זאת התקדמות",
      "יש בי חוזקות",
      "בעבר כבר התמודדתי עם אתגרים",
      "מצב הרוח משתנה כמו מזג האוויר שאינו קבוע",
      "רגשות חולפים ומשתנים",
      "אני מסוגלת",
      "יש לי כוחות",
      "אני לומדת להירגע",
      "אחרי הירידות באות העליות",
      "זה בסדר לבכות",
      "תודה על היש",
      "קחי רגע לחייך",
      "לזכור לנשום",
      "שגרה מייצרת יציבות",
      "תנועה מוציאה מיקפאון",
      "זה בסדר לבקש עזרה",
      "זה בסדר לא להיות בסדר",
      "שמור על הקצב שנכון לך",
      "מה נותן לך כוח להמשיך?"
    ],
    "other": [
      "מה יעזור לי כעת, גם צעדים קטנים זאת התקדמות",
      "יש בי חוזקות",
      "בעבר כבר התמודדתי עם אתגרים",
      "מצב הרוח משתנה כמו מזג האוויר שאינו קבוע",
      "רגשות חולפים ומשתנים",
      "אני מסוגל.ת",
      "יש לי כוחות",
      "אני לומד להירגע",
      "אחרי הירידות באות העליות",
      "זה בסדר לבכות",
      "תודה על היש",
      "קח.י רגע לחייך",
      "לזכור לנשום",
      "שגרה מייצרת יציבות",
      "תנועה מוציאה מיקפאון",
      "זה בסדר לבקש עזרה",
      "זה בסדר לא להיות בסדר",
      "שמור על הקצב שנכון לך",
      "מה נותן לך כוח להמשיך?"
    ],
  },
  "en": {
    "male": [
      "What will help me right now, even small steps are progress.",
      "I have strengths.",
      "I have faced challenges in the past.",
      "My mood changes like the weather, which is not constant.",
      "Emotions are fleeting and change.",
      "I am capable.",
      "I have strength.",
      "I am learning to relax.",
      "After the lows, the highs come.",
      "It's okay to cry.",
      "Thank you for what I have.",
      "Take a moment to smile.",
      "Remember to breathe.",
      "Routine creates stability.",
      "Movement breaks the stagnation.",
      "It's okay to ask for help.",
      "It's okay not to be okay.",
      "Keep the pace that feels right for you.",
      "What gives you the strength to keep going?"
    ],
    "female": [
      "What will help me right now, even small steps are progress.",
      "I have strengths.",
      "I have faced challenges in the past.",
      "My mood changes like the weather, which is not constant.",
      "Emotions are fleeting and change.",
      "I am capable.",
      "I have strength.",
      "I am learning to relax.",
      "After the lows, the highs come.",
      "It's okay to cry.",
      "Thank you for what I have.",
      "Take a moment to smile.",
      "Remember to breathe.",
      "Routine creates stability.",
      "Movement breaks the stagnation.",
      "It's okay to ask for help.",
      "It's okay not to be okay.",
      "Keep the pace that feels right for you.",
      "What gives you the strength to keep going?"
    ],
    "other": [
      "What will help me right now, even small steps are progress.",
      "I have strengths.",
      "I have faced challenges in the past.",
      "My mood changes like the weather, which is not constant.",
      "Emotions are fleeting and change.",
      "I am capable.",
      "I have strength.",
      "I am learning to relax.",
      "After the lows, the highs come.",
      "It's okay to cry.",
      "Thank you for what I have.",
      "Take a moment to smile.",
      "Remember to breathe.",
      "Routine creates stability.",
      "Movement breaks the stagnation.",
      "It's okay to ask for help.",
      "It's okay not to be okay.",
      "Keep the pace that feels right for you.",
      "What gives you the strength to keep going?"
    ]
  }
};
Map<String, Map<String, List<String>>> thanksList = {
  "he": {
    "male": [
      "תודה שיש לי רגעים קלים יותר",
      "תודה על ארוחה טובה",
      "תודה שהצלחתי להתאמן",
      "תודה על שיחה טובה",
      "תודה שישנתי טוב",
      "תודה שהצלחתי",
      "תודה על בילוי עם",
      "תודה על מזג האוויר",
      "תודה שיש לי בית",
      "תודה על בריאות טובה",
      "תודה על משפחה",
      "תודה על חברים"
    ],
    "female": [
      "תודה שיש לי רגעים קלים יותר",
      "תודה על ארוחה טובה",
      "תודה שהצלחתי להתאמן",
      "תודה על שיחה טובה",
      "תודה שישנתי טוב",
      "תודה שהצלחתי",
      "תודה על בילוי עם",
      "תודה על מזג האוויר",
      "תודה שיש לי בית",
      "תודה על בריאות טובה",
      "תודה על משפחה",
      "תודה על חברים"
    ],
    "other": [
      "תודה שיש לי רגעים קלים יותר",
      "תודה על ארוחה טובה",
      "תודה שהצלחתי להתאמן",
      "תודה על שיחה טובה",
      "תודה שישנתי טוב",
      "תודה שהצלחתי",
      "תודה על בילוי עם",
      "תודה על מזג האוויר",
      "תודה שיש לי בית",
      "תודה על בריאות טובה",
      "תודה על משפחה",
      "תודה על חברים"
    ],
  },
  "en": {
    "male": [
      "Thank you for the easier moments I have.",
      "Thank you for a good meal.",
      "Thank you for being able to exercise.",
      "Thank you for a good conversation.",
      "Thank you for sleeping well.",
      "Thank you for being successful.",
      "Thank you for spending time with.",
      "Thank you for the weather.",
      "Thank you for having a home.",
      "Thank you for good health.",
      "Thank you for family.",
      "Thank you for friends."
    ],
    "female": [
      "Thank you for the easier moments I have.",
      "Thank you for a good meal.",
      "Thank you for being able to exercise.",
      "Thank you for a good conversation.",
      "Thank you for sleeping well.",
      "Thank you for being successful.",
      "Thank you for spending time with.",
      "Thank you for the weather.",
      "Thank you for having a home.",
      "Thank you for good health.",
      "Thank you for family.",
      "Thank you for friends."
    ],
    "other": [
      "Thank you for the easier moments I have.",
      "Thank you for a good meal.",
      "Thank you for being able to exercise.",
      "Thank you for a good conversation.",
      "Thank you for sleeping well.",
      "Thank you for being successful.",
      "Thank you for spending time with.",
      "Thank you for the weather.",
      "Thank you for having a home.",
      "Thank you for good health.",
      "Thank you for family.",
      "Thank you for friends."
    ]
  }
};
Map<String, Map<String, List<String>>> traitsList = {
  "he": {
    "male": [
      "מה יעזור לי כעת, גם צעדים קטנים זאת התקדמות",
      "יש בי חוזקות",
      "בעבר כבר התמודדתי עם אתגרים",
      "מצב הרוח משתנה כמו מזג האוויר שאינו קבוע",
      "רגשות חולפים ומשתנים",
      "אני מסוגל",
      "יש לי כוחות",
      "אני לומד להירגע",
      "אחרי הירידות באות העליות",
      "זה בסדר לבכות",
      "תודה על היש",
      "קח רגע לחייך",
      "לזכור לנשום",
      "שגרה מייצרת יציבות",
      "תנועה מוציאה מיקפאון",
      "זה בסדר לבקש עזרה",
      "זה בסדר לא להיות בסדר",
      "שמור על הקצב שנכון לך",
      "מה נותן לך כוח להמשיך?"
    ],
    "female": [
      "מה יעזור לי כעת, גם צעדים קטנים זאת התקדמות",
      "יש בי חוזקות",
      "בעבר כבר התמודדתי עם אתגרים",
      "מצב הרוח משתנה כמו מזג האוויר שאינו קבוע",
      "רגשות חולפים ומשתנים",
      "אני מסוגלת",
      "יש לי כוחות",
      "אני לומדת להירגע",
      "אחרי הירידות באות העליות",
      "זה בסדר לבכות",
      "תודה על היש",
      "קחי רגע לחייך",
      "לזכור לנשום",
      "שגרה מייצרת יציבות",
      "תנועה מוציאה מיקפאון",
      "זה בסדר לבקש עזרה",
      "זה בסדר לא להיות בסדר",
      "שמור על הקצב שנכון לך",
      "מה נותן לך כוח להמשיך?"
    ],
    "other": [
      "מה יעזור לי כעת, גם צעדים קטנים זאת התקדמות",
      "יש בי חוזקות",
      "בעבר כבר התמודדתי עם אתגרים",
      "מצב הרוח משתנה כמו מזג האוויר שאינו קבוע",
      "רגשות חולפים ומשתנים",
      "אני מסוגל.ת",
      "יש לי כוחות",
      "אני לומד להירגע",
      "אחרי הירידות באות העליות",
      "זה בסדר לבכות",
      "תודה על היש",
      "קח.י רגע לחייך",
      "לזכור לנשום",
      "שגרה מייצרת יציבות",
      "תנועה מוציאה מיקפאון",
      "זה בסדר לבקש עזרה",
      "זה בסדר לא להיות בסדר",
      "שמור על הקצב שנכון לך",
      "מה נותן לך כוח להמשיך?"
    ],
  },
  "en": {
    "male": [
      "What will help me right now, even small steps are progress.",
      "I have strengths.",
      "I have faced challenges in the past.",
      "My mood changes like the weather, which is not constant.",
      "Emotions are fleeting and change.",
      "I am capable.",
      "I have strength.",
      "I am learning to relax.",
      "After the lows, the highs come.",
      "It's okay to cry.",
      "Thank you for what I have.",
      "Take a moment to smile.",
      "Remember to breathe.",
      "Routine creates stability.",
      "Movement breaks the stagnation.",
      "It's okay to ask for help.",
      "It's okay not to be okay.",
      "Keep the pace that feels right for you.",
      "What gives you the strength to keep going?"
    ],
    "female": [
      "What will help me right now, even small steps are progress.",
      "I have strengths.",
      "I have faced challenges in the past.",
      "My mood changes like the weather, which is not constant.",
      "Emotions are fleeting and change.",
      "I am capable.",
      "I have strength.",
      "I am learning to relax.",
      "After the lows, the highs come.",
      "It's okay to cry.",
      "Thank you for what I have.",
      "Take a moment to smile.",
      "Remember to breathe.",
      "Routine creates stability.",
      "Movement breaks the stagnation.",
      "It's okay to ask for help.",
      "It's okay not to be okay.",
      "Keep the pace that feels right for you.",
      "What gives you the strength to keep going?"
    ],
    "other": [
      "What will help me right now, even small steps are progress.",
      "I have strengths.",
      "I have faced challenges in the past.",
      "My mood changes like the weather, which is not constant.",
      "Emotions are fleeting and change.",
      "I am capable.",
      "I have strength.",
      "I am learning to relax.",
      "After the lows, the highs come.",
      "It's okay to cry.",
      "Thank you for what I have.",
      "Take a moment to smile.",
      "Remember to breathe.",
      "Routine creates stability.",
      "Movement breaks the stagnation.",
      "It's okay to ask for help.",
      "It's okay not to be okay.",
      "Keep the pace that feels right for you.",
      "What gives you the strength to keep going?"
    ]
  }
};
Map<String, Map<String, List<String>>> difficultEventsList = {
  "he": {
    "male": [
      "מה יעזור לי כעת",
      "גם צעדים קטנים זאת התקדמות",
      "יש בי חוזקות",
      "בעבר כבר התמודדתי עם אתגרים",
      "מצב הרוח משתנה כמו מזג האוויר שאינו קבוע",
      "רגשות חולפים ומשתנים",
      "אני מסוגל",
      "יש לי כוחות",
      "אני לומד להירגע",
      "אחרי הירידות באות העליות",
      "זה בסדר לבכות",
      "תודה על היש",
      "קח רגע לחייך",
      "לזכור לנשום",
      "שגרה מייצרת יציבות",
      "תנועה מוציאה מיקפאון",
      "זה בסדר לבקש עזרה",
      "זה בסדר לא להיות בסדר",
      "שמור על הקצב שנכון לך",
      "מה נותן לך כוח להמשיך?"
    ],
    "female": [
      "מה יעזור לי כעת",
      "גם צעדים קטנים זאת התקדמות",
      "יש בי חוזקות",
      "בעבר כבר התמודדתי עם אתגרים",
      "מצב הרוח משתנה כמו מזג האוויר שאינו קבוע",
      "רגשות חולפים ומשתנים",
      "אני מסוגלת",
      "יש לי כוחות",
      "אני לומד להירגע",
      "אחרי הירידות באות העליות",
      "זה בסדר לבכות",
      "תודה על היש",
      "קחי רגע לחייך",
      "לזכור לנשום",
      "שגרה מייצרת יציבות",
      "תנועה מוציאה מיקפאון",
      "זה בסדר לבקש עזרה",
      "זה בסדר לא להיות בסדר",
      "שמור על הקצב שנכון לך",
      "מה נותן לך כוח להמשיך?"
    ],
    "other": [
      "מה יעזור לי כעת",
      "גם צעדים קטנים זאת התקדמות",
      "יש בי חוזקות",
      "בעבר כבר התמודדתי עם אתגרים",
      "מצב הרוח משתנה כמו מזג האוויר שאינו קבוע",
      "רגשות חולפים ומשתנים",
      "אני מסוגל.ת",
      "יש לי כוחות",
      "אני לומד להירגע",
      "אחרי הירידות באות העליות",
      "זה בסדר לבכות",
      "תודה על היש",
      "קח.י רגע לחייך",
      "לזכור לנשום",
      "שגרה מייצרת יציבות",
      "תנועה מוציאה מיקפאון",
      "זה בסדר לבקש עזרה",
      "זה בסדר לא להיות בסדר",
      "שמור על הקצב שנכון לך",
      "מה נותן לך כוח להמשיך?"
    ],
  },
  "en": {
    "male": [
      "What will help me now",
      "Even small steps are progress",
      "I have strengths",
      "I have already faced challenges in the past",
      "Mood changes like the weather, which is not constant",
      "Feelings pass and change",
      "I am capable",
      "I have strength",
      "I am learning to relax",
      "After the lows, come the highs",
      "It’s okay to cry",
      "Thank you for what is",
      "Take a moment to smile",
      "Remember to breathe",
      "Routine creates stability",
      "Movement breaks stagnation",
      "It’s okay to ask for help",
      "It’s okay not to be okay",
      "Stick to the pace that is right for you",
      "What gives you the strength to keep going?"
    ],
    "female": [
      "What will help me now",
      "Even small steps are progress",
      "I have strengths",
      "I have already faced challenges in the past",
      "Mood changes like the weather, which is not constant",
      "Feelings pass and change",
      "I am capable",
      "I have strength",
      "I am learning to relax",
      "After the lows, come the highs",
      "It’s okay to cry",
      "Thank you for what is",
      "Take a moment to smile",
      "Remember to breathe",
      "Routine creates stability",
      "Movement breaks stagnation",
      "It’s okay to ask for help",
      "It’s okay not to be okay",
      "Stick to the pace that is right for you",
      "What gives you the strength to keep going?"
    ],
    "other": [
      "What will help me now",
      "Even small steps are progress",
      "I have strengths",
      "I have already faced challenges in the past",
      "Mood changes like the weather, which is not constant",
      "Feelings pass and change",
      "I am capable",
      "I have strength",
      "I am learning to relax",
      "After the lows, come the highs",
      "It’s okay to cry",
      "Thank you for what is",
      "Take a moment to smile",
      "Remember to breathe",
      "Routine creates stability",
      "Movement breaks stagnation",
      "It’s okay to ask for help",
      "It’s okay not to be okay",
      "Stick to the pace that is right for you",
      "What gives you the strength to keep going?"
    ]
  }
};
Map<String, Map<String, List<String>>> makeSaferList = {
  "he": {
    "male": [
      "שיעזרו לי עם פרוייקטים משותפים שנותנים משמעות",
      "לברר מה קורה איתי ולחשוב איתי על דרך ההתמודדות",
      "שיזמינו אותי לעשייה משותפת",
      "שיבקרו אותי",
      "שיזמינו אותי לנגינה או משחק",
      "שיזמינו אותי לפעילות משותפת",
      "שיעודדו אותי לישון מספיק",
      "לא להישאר לבד",
      "שיזמינו אותי לארוחה",
      "לקבל אוכל מזין",
      "לבקש ממישהו שאני סומכ.ת עליו להישאר איתי",
      "שיזמינו אותי להליכה או טיול או לפעילות גופנית",
      "להימנע ממקומות שגורמים לי להרגיש לא בטוח",
      "להשאיר אצלי כמות קטנה בלבד של התרופות שלי",
      "ואת השאר להפקיד בידי מישהו שאני סומכת עליו",
      "לבקש ממישהו אחר להרחיק ממני דברים שעלולים לשמש אותי לפגוע בעצמי",
      "שישאלו אותי"
    ],
    "female": [
      "שיעזרו לי עם פרוייקטים משותפים שנותנים משמעות",
      "לברר מה קורה איתי ולחשוב איתי על דרך ההתמודדות",
      "שיזמינו אותי לעשייה משותפת",
      "שיבקרו אותי",
      "שיזמינו אותי לנגינה או משחק",
      "שיזמינו אותי לפעילות משותפת",
      "שיעודדו אותי לישון מספיק",
      "לא להישאר לבד",
      "שיזמינו אותי לארוחה",
      "לקבל אוכל מזין",
      "לבקש ממישהו שאני סומכ.ת עליו להישאר איתי",
      "שיזמינו אותי להליכה או טיול או לפעילות גופנית",
      "להימנע ממקומות שגורמים לי להרגיש לא בטוחה",
      "להשאיר אצלי כמות קטנה בלבד של התרופות שלי",
      "ואת השאר להפקיד בידי מישהו שאני סומכת עליו",
      "לבקש ממישהו אחר להרחיק ממני דברים שעלולים לשמש אותי לפגוע בעצמי",
      "שישאלו אותי"
    ],
    "other": [
      "שיעזרו לי עם פרוייקטים משותפים שנותנים משמעות",
      "לברר מה קורה איתי ולחשוב איתי על דרך ההתמודדות",
      "שיזמינו אותי לעשייה משותפת",
      "שיבקרו אותי",
      "שיזמינו אותי לנגינה או משחק",
      "שיזמינו אותי לפעילות משותפת",
      "שיעודדו אותי לישון מספיק",
      "לא להישאר לבד",
      "שיזמינו אותי לארוחה",
      "לקבל אוכל מזין",
      "לבקש ממישהו שאני סומכ.ת עליו להישאר איתי",
      "שיזמינו אותי להליכה או טיול או לפעילות גופנית",
      "להימנע ממקומות שגורמים לי להרגיש לא בטוח.ה",
      "להשאיר אצלי כמות קטנה בלבד של התרופות שלי",
      "ואת השאר להפקיד בידי מישהו שאני סומכ.ת עליו",
      "לבקש ממישהו אחר להרחיק ממני דברים שעלולים לשמש אותי לפגוע בעצמי",
      "שישאלו אותי"
    ],
  },
  "en": {
    "male": [
      "They will help me with joint projects that give meaning",
      "To inquire about what’s going on with me and think with me about how to cope",
      "They will invite me to do something together",
      "They will visit me",
      "They will invite me to play music or games",
      "They will invite me to a shared activity",
      "They will encourage me to sleep enough",
      "Not to stay alone",
      "They will invite me to a meal",
      "To receive nutritious food",
      "To ask someone I trust to stay with me",
      "They will invite me for a walk or trip or physical activity",
      "To avoid places that make me feel unsafe",
      "To keep only a small amount of my medications with me",
      "And entrust the rest to someone I trust",
      "To ask someone else to remove things that could be used to harm myself",
      "To ask me"
    ],
    "female": [
      "They will help me with joint projects that give meaning",
      "To inquire about what’s going on with me and think with me about how to cope",
      "They will invite me to do something together",
      "They will visit me",
      "They will invite me to play music or games",
      "They will invite me to a shared activity",
      "They will encourage me to sleep enough",
      "Not to stay alone",
      "They will invite me to a meal",
      "To receive nutritious food",
      "To ask someone I trust to stay with me",
      "They will invite me for a walk or trip or physical activity",
      "To avoid places that make me feel unsafe",
      "To keep only a small amount of my medications with me",
      "And entrust the rest to someone I trust",
      "To ask someone else to remove things that could be used to harm myself",
      "To ask me"
    ],
    "other": [
      "They will help me with joint projects that give meaning",
      "To inquire about what’s going on with me and think with me about how to cope",
      "They will invite me to do something together",
      "They will visit me",
      "They will invite me to play music or games",
      "They will invite me to a shared activity",
      "They will encourage me to sleep enough",
      "Not to stay alone",
      "They will invite me to a meal",
      "To receive nutritious food",
      "To ask someone I trust to stay with me",
      "They will invite me for a walk or trip or physical activity",
      "To avoid places that make me feel unsafe",
      "To keep only a small amount of my medications with me",
      "And entrust the rest to someone I trust",
      "To ask someone else to remove things that could be used to harm myself",
      "To ask me"
    ]
  }
};
Map<String, Map<String, List<String>>> feelBetterList = {
  "he": {
    "male": [
      "מיינדפולנס",
      "זמן זוגי/חברתי קבוע בשבוע",
      "רשימת חוזקות ומעלות",
      "יומן הכרת תודה",
      "להגיד מתי יש לי פנות להקשיב",
      "להאט ולהשתדל לא להעמיס עלי יותר מידי",
      "להתנתק ממשימות היום יום וממסכים",
      "לראות אור שמש",
      "לצאת לטבע",
      "מנוחה",
      "זמן שקט לעצמי",
      "לצחצח שיניים כדי לקבל טעם רענן בפה",
      "או לקחת מסטיק",
      "לקבל חיבוק ממישהו שאני סומך עליו",
      "לומר לעצמי: 'אני חשוב/ משמעותי / בעל ערך'",
      "'יש אנשים שאוהבים אותי'",
      "להתמקד בנשימה / בתחושות הגופניות",
      "לקחת הפסקה על ידי שינוי המיקום שלי (למשל, לעבור לחדר אחר בבית)",
      "לצאת להליכה קצרה בחוץ",
      "לצאת לנשום קצת אוויר צח (מחוץ לבית או אפילו מהמרפסת)",
      "לצפות בקליפים"
    ],
    "female": [
      "מיינדפולנס",
      "זמן זוגי/חברתי קבוע בשבוע",
      "רשימת חוזקות ומעלות",
      "יומן הכרת תודה",
      "להגיד מתי יש לי פנות להקשיב",
      "להאט ולהשתדל לא להעמיס עלי יותר מידי",
      "להתנתק ממשימות היום יום וממסכים",
      "לראות אור שמש",
      "לצאת לטבע",
      "מנוחה",
      "זמן שקט לעצמי",
      "לצחצח שיניים כדי לקבל טעם רענן בפה",
      "או לקחת מסטיק",
      "לקבל חיבוק ממישהו שאני סומכ.ת עליו",
      "לומר לעצמי: 'אני חשובה/ משמעותית / בעלת ערך'",
      "'יש אנשים שאוהבים אותי'",
      "להתמקד בנשימה / בתחושות הגופניות",
      "לקחת הפסקה על ידי שינוי המיקום שלי (למשל, לעבור לחדר אחר בבית)",
      "לצאת להליכה קצרה בחוץ",
      "לצאת לנשום קצת אוויר צח (מחוץ לבית או אפילו מהמרפסת)",
      "לצפות בקליפים"
    ],
    "other": [
      "מיינדפולנס",
      "זמן זוגי/חברתי קבוע בשבוע",
      "רשימת חוזקות ומעלות",
      "יומן הכרת תודה",
      "להגיד מתי יש לי פנות להקשיב",
      "להאט ולהשתדל לא להעמיס עלי יותר מידי",
      "להתנתק ממשימות היום יום וממסכים",
      "לראות אור שמש",
      "לצאת לטבע",
      "מנוחה Down Time",
      "זמן שקט לעצמי",
      "לצחצח שיניים כדי לקבל טעם רענן בפה",
      "או לקחת מסטיק",
      "לקבל חיבוק ממישהו שאני סומכ.ת עליו",
      "לומר לעצמי: 'אני חשוב.ה/ משמעותי.ת / בעל.ת ערך'",
      "'יש אנשים שאוהבים אותי'",
      "להתמקד בנשימה / בתחושות הגופניות",
      "לקחת הפסקה על ידי שינוי המיקום שלי (למשל, לעבור לחדר אחר בבית)",
      "לצאת להליכה קצרה בחוץ",
      "לצאת לנשום קצת אוויר צח (מחוץ לבית או אפילו מהמרפסת)",
      "לצפות בקליפים"
    ],
  },
  "en": {
    "male": [
      "Mindfulness",
      "Regular couple/social time each week",
      "List of strengths and virtues",
      "Gratitude journal",
      "To say when I am available to listen",
      "To slow down and try not to overload myself",
      "To disconnect from daily tasks and screens",
      "To see sunlight",
      "To go out into nature",
      "Down Time",
      "Quiet time for myself",
      "To brush my teeth to get a fresh taste in my mouth",
      "Or take gum",
      "To receive a hug from someone I trust",
      "To tell myself: 'I am important/significant/valuable'",
      "'There are people who love me'",
      "To focus on breathing / bodily sensations",
      "To take a break by changing my location (for example, moving to another room in the house)",
      "To go for a short walk outside",
      "To go out and breathe some fresh air (outside the house or even from the balcony)",
      "To watch clips"
    ],
    "female": [
      "Mindfulness",
      "Regular couple/social time each week",
      "List of strengths and virtues",
      "Gratitude journal",
      "To say when I am available to listen",
      "To slow down and try not to overload myself",
      "To disconnect from daily tasks and screens",
      "To see sunlight",
      "To go out into nature",
      "Down Time",
      "Quiet time for myself",
      "To brush my teeth to get a fresh taste in my mouth",
      "Or take gum",
      "To receive a hug from someone I trust",
      "To tell myself: 'I am important/significant/valuable'",
      "'There are people who love me'",
      "To focus on breathing / bodily sensations",
      "To take a break by changing my location (for example, moving to another room in the house)",
      "To go for a short walk outside",
      "To go out and breathe some fresh air (outside the house or even from the balcony)",
      "To watch clips"
    ],
    "other": [
      "Mindfulness",
      "Regular couple/social time each week",
      "List of strengths and virtues",
      "Gratitude journal",
      "To say when I am available to listen",
      "To slow down and try not to overload myself",
      "To disconnect from daily tasks and screens",
      "To see sunlight",
      "To go out into nature",
      "Down Time",
      "Quiet time for myself",
      "To brush my teeth to get a fresh taste in my mouth",
      "Or take gum",
      "To receive a hug from someone I trust",
      "To tell myself: 'I am important/significant/valuable'",
      "'There are people who love me'",
      "To focus on breathing / bodily sensations",
      "To take a break by changing my location (for example, moving to another room in the house)",
      "To go for a short walk outside",
      "To go out and breathe some fresh air (outside the house or even from the balcony)",
      "To watch clips"
    ]
  }
};
Map<String, Map<String, List<String>>> distractionsList = {
  "he": {
    "male": [
      "מחשבות אובדניות",
      "ביטחון עצמי נמוך",
      "תחושה שלא אכפת ממני",
      "רצון להתחפר ולהתחבא או להיעלם",
      "עייפות קשה",
      "ירידה בתפקוד",
      "חוסר או ירידה בכוחות",
      "חרדות",
      "מיניות מופחתת",
      "אפאטיות או אדישות",
      "רגישות יתר",
      "האשמה עצמית",
      "פזרנות והעלאת מינון הקניות",
      "הזנחה עצמית",
      "ביטחון יתר",
      "לעשות את המינימום של המינימום - וגם זה במאמץ רב",
      "תפקוד ירוד",
      "מוח רץ",
      "מחשבות מתרוצצות ומהירות",
      "חוסר ביטחון",
      "הססנות",
      "מחשבות איטיות ומבולבלות",
      "מוחצנות מוגברת",
      "השתבללות",
      "התכנסות",
      "הסתגרות",
      "מילוי כל חלל הזמן",
      "חשש מזמן לבד",
      "חשש מריק",
      "שימוש רב במדיות שונות",
      "יותר כאבי ראש",
      "תיאבון יתר",
      "שינה לא סדירה",
      "נדודי שינה או שינה מעוטה",
    ],
    "female": [
      "מחשבות אובדניות",
      "ביטחון עצמי נמוך",
      "תחושה שלא אכפת ממני",
      "רצון להתחפר ולהתחבא או להיעלם",
      "עייפות קשה",
      "ירידה בתפקוד",
      "חוסר או ירידה בכוחות",
      "חרדות",
      "מיניות מופחתת",
      "אפאטיות או אדישות",
      "רגישות יתר",
      "האשמה עצמית",
      "פזרנות והעלאת מינון הקניות",
      "הזנחה עצמית",
      "ביטחון יתר",
      "לעשות את המינימום של המינימום - וגם זה במאמץ רב",
      "תפקוד ירוד",
      "מוח רץ",
      "מחשבות מתרוצצות ומהירות",
      "חוסר ביטחון",
      "הססנות",
      "מחשבות איטיות ומבולבלות",
      "מוחצנות מוגברת",
      "השתבללות",
      "התכנסות",
      "הסתגרות",
      "מילוי כל חלל הזמן",
      "חשש מזמן לבד",
      "חשש מריק",
      "שימוש רב במדיות שונות",
      "יותר כאבי ראש",
      "תיאבון יתר",
      "שינה לא סדירה",
      "נדודי שינה או שינה מעוטה",
    ],
    "other": [
      "מחשבות אובדניות",
      "ביטחון עצמי נמוך",
      "תחושה שלא אכפת ממני",
      "רצון להתחפר ולהתחבא או להיעלם",
      "עייפות קשה",
      "ירידה בתפקוד",
      "חוסר או ירידה בכוחות",
      "חרדות",
      "מיניות מופחתת",
      "אפאטיות או אדישות",
      "רגישות יתר",
      "האשמה עצמית",
      "פזרנות והעלאת מינון הקניות",
      "הזנחה עצמית",
      "ביטחון יתר",
      "לעשות את המינימום של המינימום - וגם זה במאמץ רב",
      "תפקוד ירוד",
      "מוח רץ",
      "מחשבות מתרוצצות ומהירות",
      "חוסר ביטחון",
      "הססנות",
      "מחשבות איטיות ומבולבלות",
      "מוחצנות מוגברת",
      "השתבללות",
      "התכנסות",
      "הסתגרות",
      "מילוי כל חלל הזמן",
      "חשש מזמן לבד",
      "חשש מריק",
      "שימוש רב במדיות שונות",
      "יותר כאבי ראש",
      "תיאבון יתר",
      "שינה לא סדירה",
      "נדודי שינה או שינה מעוטה",
    ],
  },
  "en": {
    "male": [
      "Suicidal thoughts",
      "Low self-esteem",
      "Feeling that no one cares about me",
      "Desire to bury myself, hide, or disappear",
      "Severe fatigue",
      "Decline in functioning",
      "Lack or decrease in strength",
      "Anxiety",
      "Reduced sexuality",
      "Apathy or indifference",
      "Over-sensitivity",
      "Self-blame",
      "Wastefulness and increased spending",
      "Self-neglect",
      "Excessive confidence",
      "Doing the minimum of the minimum - and even that with great effort",
      "Impaired functioning",
      "Racing mind",
      "Racing and fast thoughts",
      "Lack of confidence",
      "Indecisiveness",
      "Slow and confused thoughts",
      "Increased extroversion",
      "Withdrawal",
      "Retreat",
      "Isolation",
      "Filling all the time",
      "Fear of being alone",
      "Fear of emptiness",
      "Excessive use of various media",
      "More headaches",
      "Increased appetite",
      "Irregular sleep",
      "Insomnia or minimal sleep"
    ],
    "female": [
      "Suicidal thoughts",
      "Low self-esteem",
      "Feeling that no one cares about me",
      "Desire to bury myself, hide, or disappear",
      "Severe fatigue",
      "Decline in functioning",
      "Lack or decrease in strength",
      "Anxiety",
      "Reduced sexuality",
      "Apathy or indifference",
      "Over-sensitivity",
      "Self-blame",
      "Wastefulness and increased spending",
      "Self-neglect",
      "Excessive confidence",
      "Doing the minimum of the minimum - and even that with great effort",
      "Impaired functioning",
      "Racing mind",
      "Racing and fast thoughts",
      "Lack of confidence",
      "Indecisiveness",
      "Slow and confused thoughts",
      "Increased extroversion",
      "Withdrawal",
      "Retreat",
      "Isolation",
      "Filling all the time",
      "Fear of being alone",
      "Fear of emptiness",
      "Excessive use of various media",
      "More headaches",
      "Increased appetite",
      "Irregular sleep",
      "Insomnia or minimal sleep"
    ],
    "other": [
      "Suicidal thoughts",
      "Low self-esteem",
      "Feeling that no one cares about me",
      "Desire to bury myself, hide, or disappear",
      "Severe fatigue",
      "Decline in functioning",
      "Lack or decrease in strength",
      "Anxiety",
      "Reduced sexuality",
      "Apathy or indifference",
      "Over-sensitivity",
      "Self-blame",
      "Wastefulness and increased spending",
      "Self-neglect",
      "Excessive confidence",
      "Doing the minimum of the minimum - and even that with great effort",
      "Impaired functioning",
      "Racing mind",
      "Racing and fast thoughts",
      "Lack of confidence",
      "Indecisiveness",
      "Slow and confused thoughts",
      "Increased extroversion",
      "Withdrawal",
      "Retreat",
      "Isolation",
      "Filling all the time",
      "Fear of being alone",
      "Fear of emptiness",
      "Excessive use of various media",
      "More headaches",
      "Increased appetite",
      "Irregular sleep",
      "Insomnia or minimal sleep"
    ]
  }
};
