// Mocks generated by Mockito 5.4.6 from annotations
// in mazilon/test/MenuTest/shareAndDownload/share_and_download_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i5;
import 'dart:ui' as _i14;

import 'package:flutter/foundation.dart' as _i4;
import 'package:flutter/material.dart' as _i3;
import 'package:image_picker/image_picker.dart' as _i19;
import 'package:mazilon/AnalyticsService.dart' as _i20;
import 'package:mazilon/file_service.dart' as _i6;
import 'package:mazilon/global_enums.dart' as _i9;
import 'package:mazilon/pages/FeelGood/image_picker_service_impl.dart' as _i18;
import 'package:mazilon/pages/WellnessTools/VideoPlayerPageFactory.dart'
    as _i17;
import 'package:mazilon/util/appInformation.dart' as _i15;
import 'package:mazilon/util/notification_preference.dart' as _i13;
import 'package:mazilon/util/persistent_memory_service.dart' as _i2;
import 'package:mazilon/util/personal_plan_export_snapshot.dart' as _i10;
import 'package:mazilon/util/userInformation.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:share_plus/share_plus.dart' as _i8;
import 'package:shared_preferences/shared_preferences.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePersistentMemoryService_0 extends _i1.SmartFake
    implements _i2.PersistentMemoryService {
  _FakePersistentMemoryService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWidget_1 extends _i1.SmartFake implements _i3.Widget {
  _FakeWidget_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeFile_2 extends _i1.SmartFake implements _i5.File {
  _FakeFile_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileService extends _i1.Mock implements _i6.FileService {
  @override
  _i7.Future<_i8.ShareResult?> share(
    String? message,
    List<dynamic>? titles,
    List<dynamic>? subTitles,
    Map<String, String>? texts,
    _i9.ShareFileType? saveFormat, {
    required String? mainTitle,
    required String? textDirection,
    _i2.PersistentMemoryService? memoryService,
    _i10.PersonalPlanExportSnapshot? snapshot,
    Set<String>? approvedPdfHosts,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #share,
              [message, titles, subTitles, texts, saveFormat],
              {
                #mainTitle: mainTitle,
                #textDirection: textDirection,
                #memoryService: memoryService,
                #snapshot: snapshot,
                #approvedPdfHosts: approvedPdfHosts,
              },
            ),
            returnValue: _i7.Future<_i8.ShareResult?>.value(),
            returnValueForMissingStub: _i7.Future<_i8.ShareResult?>.value(),
          )
          as _i7.Future<_i8.ShareResult?>);

  @override
  _i7.Future<String?> download(
    List<dynamic>? titles,
    List<dynamic>? subTitles,
    Map<String, String>? texts,
    _i9.ShareFileType? saveFormat, {
    required String? mainTitle,
    required String? textDirection,
    _i2.PersistentMemoryService? memoryService,
    _i10.PersonalPlanExportSnapshot? snapshot,
    Set<String>? approvedPdfHosts,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [titles, subTitles, texts, saveFormat],
              {
                #mainTitle: mainTitle,
                #textDirection: textDirection,
                #memoryService: memoryService,
                #snapshot: snapshot,
                #approvedPdfHosts: approvedPdfHosts,
              },
            ),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<bool> shareTextOnly(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#shareTextOnly, [message]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [UserInformation].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserInformation extends _i1.Mock implements _i11.UserInformation {
  @override
  String get localeName =>
      (super.noSuchMethod(
            Invocation.getter(#localeName),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
          )
          as String);

  @override
  String get gender =>
      (super.noSuchMethod(
            Invocation.getter(#gender),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#gender),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#gender),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get age =>
      (super.noSuchMethod(
            Invocation.getter(#age),
            returnValue: _i12.dummyValue<String>(this, Invocation.getter(#age)),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#age),
            ),
          )
          as String);

  @override
  String get location =>
      (super.noSuchMethod(
            Invocation.getter(#location),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#location),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#location),
            ),
          )
          as String);

  @override
  bool get binary =>
      (super.noSuchMethod(
            Invocation.getter(#binary),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get disclaimerSigned =>
      (super.noSuchMethod(
            Invocation.getter(#disclaimerSigned),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<String> get difficultEvents =>
      (super.noSuchMethod(
            Invocation.getter(#difficultEvents),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> get positiveTraits =>
      (super.noSuchMethod(
            Invocation.getter(#positiveTraits),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> get makeSafer =>
      (super.noSuchMethod(
            Invocation.getter(#makeSafer),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> get feelBetter =>
      (super.noSuchMethod(
            Invocation.getter(#feelBetter),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> get distractions =>
      (super.noSuchMethod(
            Invocation.getter(#distractions),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> get safeEnvironment =>
      (super.noSuchMethod(
            Invocation.getter(#safeEnvironment),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> get dreamsAndGoals =>
      (super.noSuchMethod(
            Invocation.getter(#dreamsAndGoals),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> get dreamsAndGoalsSelectionSources =>
      (super.noSuchMethod(
            Invocation.getter(#dreamsAndGoalsSelectionSources),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool get loggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#loggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get authDecisionMade =>
      (super.noSuchMethod(
            Invocation.getter(#authDecisionMade),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get displayName =>
      (super.noSuchMethod(
            Invocation.getter(#displayName),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
          )
          as String);

  @override
  Map<String, _i13.NotificationPreference> get notificationPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#notificationPreferences),
            returnValue: <String, _i13.NotificationPreference>{},
            returnValueForMissingStub: <String, _i13.NotificationPreference>{},
          )
          as Map<String, _i13.NotificationPreference>);

  @override
  _i11.DarkModePreference get darkModePreference =>
      (super.noSuchMethod(
            Invocation.getter(#darkModePreference),
            returnValue: _i11.DarkModePreference.alwaysLight,
            returnValueForMissingStub: _i11.DarkModePreference.alwaysLight,
          )
          as _i11.DarkModePreference);

  @override
  int get darkModeStartHour =>
      (super.noSuchMethod(
            Invocation.getter(#darkModeStartHour),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get darkModeStartMinute =>
      (super.noSuchMethod(
            Invocation.getter(#darkModeStartMinute),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get darkModeEndHour =>
      (super.noSuchMethod(
            Invocation.getter(#darkModeEndHour),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get darkModeEndMinute =>
      (super.noSuchMethod(
            Invocation.getter(#darkModeEndMinute),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  Map<String, List<String>> get thanks =>
      (super.noSuchMethod(
            Invocation.getter(#thanks),
            returnValue: <String, List<String>>{},
            returnValueForMissingStub: <String, List<String>>{},
          )
          as Map<String, List<String>>);

  @override
  List<MapEntry<String, String>> get customCategories =>
      (super.noSuchMethod(
            Invocation.getter(#customCategories),
            returnValue: <MapEntry<String, String>>[],
            returnValueForMissingStub: <MapEntry<String, String>>[],
          )
          as List<MapEntry<String, String>>);

  @override
  _i2.PersistentMemoryService get service =>
      (super.noSuchMethod(
            Invocation.getter(#service),
            returnValue: _FakePersistentMemoryService_0(
              this,
              Invocation.getter(#service),
            ),
            returnValueForMissingStub: _FakePersistentMemoryService_0(
              this,
              Invocation.getter(#service),
            ),
          )
          as _i2.PersistentMemoryService);

  @override
  bool get isDreamsAndGoalsSavePending =>
      (super.noSuchMethod(
            Invocation.getter(#isDreamsAndGoalsSavePending),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<void> get pendingCustomCategoriesSave =>
      (super.noSuchMethod(
            Invocation.getter(#pendingCustomCategoriesSave),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> get pendingDreamsAndGoalsSave =>
      (super.noSuchMethod(
            Invocation.getter(#pendingDreamsAndGoalsSave),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  int get dreamsAndGoalsSaveRevision =>
      (super.noSuchMethod(
            Invocation.getter(#dreamsAndGoalsSaveRevision),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  set localeName(String? value) => super.noSuchMethod(
    Invocation.setter(#localeName, value),
    returnValueForMissingStub: null,
  );

  @override
  set gender(String? value) => super.noSuchMethod(
    Invocation.setter(#gender, value),
    returnValueForMissingStub: null,
  );

  @override
  set name(String? value) => super.noSuchMethod(
    Invocation.setter(#name, value),
    returnValueForMissingStub: null,
  );

  @override
  set age(String? value) => super.noSuchMethod(
    Invocation.setter(#age, value),
    returnValueForMissingStub: null,
  );

  @override
  set location(String? value) => super.noSuchMethod(
    Invocation.setter(#location, value),
    returnValueForMissingStub: null,
  );

  @override
  set binary(bool? value) => super.noSuchMethod(
    Invocation.setter(#binary, value),
    returnValueForMissingStub: null,
  );

  @override
  set disclaimerSigned(bool? value) => super.noSuchMethod(
    Invocation.setter(#disclaimerSigned, value),
    returnValueForMissingStub: null,
  );

  @override
  set difficultEvents(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#difficultEvents, value),
    returnValueForMissingStub: null,
  );

  @override
  set positiveTraits(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#positiveTraits, value),
    returnValueForMissingStub: null,
  );

  @override
  set makeSafer(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#makeSafer, value),
    returnValueForMissingStub: null,
  );

  @override
  set feelBetter(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#feelBetter, value),
    returnValueForMissingStub: null,
  );

  @override
  set distractions(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#distractions, value),
    returnValueForMissingStub: null,
  );

  @override
  set safeEnvironment(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#safeEnvironment, value),
    returnValueForMissingStub: null,
  );

  @override
  set dreamsAndGoals(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#dreamsAndGoals, value),
    returnValueForMissingStub: null,
  );

  @override
  set dreamsAndGoalsSelectionSources(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#dreamsAndGoalsSelectionSources, value),
    returnValueForMissingStub: null,
  );

  @override
  set loggedIn(bool? value) => super.noSuchMethod(
    Invocation.setter(#loggedIn, value),
    returnValueForMissingStub: null,
  );

  @override
  set authDecisionMade(bool? value) => super.noSuchMethod(
    Invocation.setter(#authDecisionMade, value),
    returnValueForMissingStub: null,
  );

  @override
  set userId(String? value) => super.noSuchMethod(
    Invocation.setter(#userId, value),
    returnValueForMissingStub: null,
  );

  @override
  set email(String? value) => super.noSuchMethod(
    Invocation.setter(#email, value),
    returnValueForMissingStub: null,
  );

  @override
  set displayName(String? value) => super.noSuchMethod(
    Invocation.setter(#displayName, value),
    returnValueForMissingStub: null,
  );

  @override
  set notificationPreferences(
    Map<String, _i13.NotificationPreference>? value,
  ) => super.noSuchMethod(
    Invocation.setter(#notificationPreferences, value),
    returnValueForMissingStub: null,
  );

  @override
  set darkModePreference(_i11.DarkModePreference? value) => super.noSuchMethod(
    Invocation.setter(#darkModePreference, value),
    returnValueForMissingStub: null,
  );

  @override
  set darkModeStartHour(int? value) => super.noSuchMethod(
    Invocation.setter(#darkModeStartHour, value),
    returnValueForMissingStub: null,
  );

  @override
  set darkModeStartMinute(int? value) => super.noSuchMethod(
    Invocation.setter(#darkModeStartMinute, value),
    returnValueForMissingStub: null,
  );

  @override
  set darkModeEndHour(int? value) => super.noSuchMethod(
    Invocation.setter(#darkModeEndHour, value),
    returnValueForMissingStub: null,
  );

  @override
  set darkModeEndMinute(int? value) => super.noSuchMethod(
    Invocation.setter(#darkModeEndMinute, value),
    returnValueForMissingStub: null,
  );

  @override
  set thanks(Map<String, List<String>>? value) => super.noSuchMethod(
    Invocation.setter(#thanks, value),
    returnValueForMissingStub: null,
  );

  @override
  set customCategories(List<MapEntry<String, String>>? value) =>
      super.noSuchMethod(
        Invocation.setter(#customCategories, value),
        returnValueForMissingStub: null,
      );

  @override
  set service(_i2.PersistentMemoryService? value) => super.noSuchMethod(
    Invocation.setter(#service, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<List<MapEntry<String, String>>> loadCustomCategories({
    _i2.PersistentMemoryService? memoryService,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadCustomCategories, [], {
              #memoryService: memoryService,
            }),
            returnValue: _i7.Future<List<MapEntry<String, String>>>.value(
              <MapEntry<String, String>>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<MapEntry<String, String>>>.value(
                  <MapEntry<String, String>>[],
                ),
          )
          as _i7.Future<List<MapEntry<String, String>>>);

  @override
  _i7.Future<void> saveCustomCategories({
    List<MapEntry<String, String>>? categories,
    _i2.PersistentMemoryService? memoryService,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveCustomCategories, [], {
              #categories: categories,
              #memoryService: memoryService,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> reset(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#reset, [locale]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void updateGender(String? text) => super.noSuchMethod(
    Invocation.method(#updateGender, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void updateName(String? text) => super.noSuchMethod(
    Invocation.method(#updateName, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void updateAge(String? text) => super.noSuchMethod(
    Invocation.method(#updateAge, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void updateBinary(bool? value) => super.noSuchMethod(
    Invocation.method(#updateBinary, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> updateGenderAndBinary({
    required String? gender,
    required bool? isBinary,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateGenderAndBinary, [], {
              #gender: gender,
              #isBinary: isBinary,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void updateDifficultEvents(List<String>? value) => super.noSuchMethod(
    Invocation.method(#updateDifficultEvents, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateMakeSafer(List<String>? value) => super.noSuchMethod(
    Invocation.method(#updateMakeSafer, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateFeelBetter(List<String>? value) => super.noSuchMethod(
    Invocation.method(#updateFeelBetter, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateDistractions(List<String>? value) => super.noSuchMethod(
    Invocation.method(#updateDistractions, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSafeEnvironment(List<String>? value) => super.noSuchMethod(
    Invocation.method(#updateSafeEnvironment, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateDreamsAndGoals(
    List<String>? value, {
    List<String>? selectionSources,
  }) => super.noSuchMethod(
    Invocation.method(
      #updateDreamsAndGoals,
      [value],
      {#selectionSources: selectionSources},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> queueDreamsAndGoalsSave() =>
      (super.noSuchMethod(
            Invocation.method(#queueDreamsAndGoalsSave, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> retryDreamsAndGoalsSave(int? revision) =>
      (super.noSuchMethod(
            Invocation.method(#retryDreamsAndGoalsSave, [revision]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> hydrateDreamsAndGoalsFromStorage(
    List<String>? selections, {
    required List<String>? storedSelectionSources,
    required List<String>? storedCustomSelections,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #hydrateDreamsAndGoalsFromStorage,
              [selections],
              {
                #storedSelectionSources: storedSelectionSources,
                #storedCustomSelections: storedCustomSelections,
              },
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> repairDreamsAndGoalsSelectionSources() =>
      (super.noSuchMethod(
            Invocation.method(#repairDreamsAndGoalsSelectionSources, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveDreamsAndGoalsWithDisclaimer({
    required int? revision,
    required bool? retry,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveDreamsAndGoalsWithDisclaimer, [], {
              #revision: revision,
              #retry: retry,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveCategorySelection(
    String? collectionName,
    List<String>? items, {
    List<String>? selectionSources,
    void Function(int)? onDreamsSaveQueued,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveCategorySelection,
              [collectionName, items],
              {
                #selectionSources: selectionSources,
                #onDreamsSaveQueued: onDreamsSaveQueued,
              },
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> prepareForPersonalPlanExport({
    _i2.PersistentMemoryService? memoryService,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#prepareForPersonalPlanExport, [], {
              #memoryService: memoryService,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> persistDisclaimerConfirmed() =>
      (super.noSuchMethod(
            Invocation.method(#persistDisclaimerConfirmed, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> persistHasFilled() =>
      (super.noSuchMethod(
            Invocation.method(#persistHasFilled, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void updateDisclaimerSigned(bool? value) => super.noSuchMethod(
    Invocation.method(#updateDisclaimerSigned, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateLoggedIn(bool? value) => super.noSuchMethod(
    Invocation.method(#updateLoggedIn, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateAuthDecisionMade(bool? value) => super.noSuchMethod(
    Invocation.method(#updateAuthDecisionMade, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateEmail(String? value) => super.noSuchMethod(
    Invocation.method(#updateEmail, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateDisplayName(String? value) => super.noSuchMethod(
    Invocation.method(#updateDisplayName, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateUserId(String? value) => super.noSuchMethod(
    Invocation.method(#updateUserId, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i13.NotificationPreference? getNotificationPreference(String? typeId) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationPreference, [typeId]),
            returnValueForMissingStub: null,
          )
          as _i13.NotificationPreference?);

  @override
  _i7.Future<void> setNotificationPreference(
    String? typeId,
    _i13.NotificationPreference? preference,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setNotificationPreference, [typeId, preference]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearNotificationPreference(String? typeId) =>
      (super.noSuchMethod(
            Invocation.method(#clearNotificationPreference, [typeId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool usesDarkModeAt(DateTime? now) =>
      (super.noSuchMethod(
            Invocation.method(#usesDarkModeAt, [now]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  DateTime? nextDarkModeBoundaryAfter(DateTime? now) =>
      (super.noSuchMethod(
            Invocation.method(#nextDarkModeBoundaryAfter, [now]),
            returnValueForMissingStub: null,
          )
          as DateTime?);

  @override
  void restoreDarkModeSettings({
    required _i11.DarkModePreference? preference,
    int? startHour,
    int? startMinute,
    int? endHour,
    int? endMinute,
  }) => super.noSuchMethod(
    Invocation.method(#restoreDarkModeSettings, [], {
      #preference: preference,
      #startHour: startHour,
      #startMinute: startMinute,
      #endHour: endHour,
      #endMinute: endMinute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> updateDarkModeSettings({
    _i11.DarkModePreference? preference,
    int? startHour,
    int? startMinute,
    int? endHour,
    int? endMinute,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDarkModeSettings, [], {
              #preference: preference,
              #startHour: startHour,
              #startMinute: startMinute,
              #endHour: endHour,
              #endMinute: endMinute,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void updateLocaleName(String? value) => super.noSuchMethod(
    Invocation.method(#updateLocaleName, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updatePositiveTraits(List<String>? value) => super.noSuchMethod(
    Invocation.method(#updatePositiveTraits, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateThanks(Map<String, List<String>>? value) => super.noSuchMethod(
    Invocation.method(#updateThanks, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateLocation(String? value) => super.noSuchMethod(
    Invocation.method(#updateLocation, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppInformation].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppInformation extends _i1.Mock implements _i15.AppInformation {
  @override
  String get disclaimerText =>
      (super.noSuchMethod(
            Invocation.getter(#disclaimerText),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#disclaimerText),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#disclaimerText),
            ),
          )
          as String);

  @override
  String get disclaimerNext =>
      (super.noSuchMethod(
            Invocation.getter(#disclaimerNext),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#disclaimerNext),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#disclaimerNext),
            ),
          )
          as String);

  @override
  String get reminderMainTitle =>
      (super.noSuchMethod(
            Invocation.getter(#reminderMainTitle),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#reminderMainTitle),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#reminderMainTitle),
            ),
          )
          as String);

  @override
  String get reminderSubTitle =>
      (super.noSuchMethod(
            Invocation.getter(#reminderSubTitle),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#reminderSubTitle),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#reminderSubTitle),
            ),
          )
          as String);

  @override
  String get homeTitleGreeting =>
      (super.noSuchMethod(
            Invocation.getter(#homeTitleGreeting),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#homeTitleGreeting),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#homeTitleGreeting),
            ),
          )
          as String);

  @override
  Map<String, String> get personalPlanMainTitle =>
      (super.noSuchMethod(
            Invocation.getter(#personalPlanMainTitle),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get personalPlanSubTitle =>
      (super.noSuchMethod(
            Invocation.getter(#personalPlanSubTitle),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get traitMainTitle =>
      (super.noSuchMethod(
            Invocation.getter(#traitMainTitle),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get traitSubTitle =>
      (super.noSuchMethod(
            Invocation.getter(#traitSubTitle),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get journalMainTitle =>
      (super.noSuchMethod(
            Invocation.getter(#journalMainTitle),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get journalSubTitle =>
      (super.noSuchMethod(
            Invocation.getter(#journalSubTitle),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get journalPopUpText =>
      (super.noSuchMethod(
            Invocation.getter(#journalPopUpText),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get positiveTraitsPopUpText =>
      (super.noSuchMethod(
            Invocation.getter(#positiveTraitsPopUpText),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get popupBack =>
      (super.noSuchMethod(
            Invocation.getter(#popupBack),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get othersuggestions =>
      (super.noSuchMethod(
            Invocation.getter(#othersuggestions),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get aboutPageText =>
      (super.noSuchMethod(
            Invocation.getter(#aboutPageText),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get returnToPlanStrings =>
      (super.noSuchMethod(
            Invocation.getter(#returnToPlanStrings),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get warningHomePageTitles =>
      (super.noSuchMethod(
            Invocation.getter(#warningHomePageTitles),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get traitsHomePageTitles =>
      (super.noSuchMethod(
            Invocation.getter(#traitsHomePageTitles),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get introductionFormFirstPage =>
      (super.noSuchMethod(
            Invocation.getter(#introductionFormFirstPage),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get introductionFormSecondPage =>
      (super.noSuchMethod(
            Invocation.getter(#introductionFormSecondPage),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get introductionFormLastPage =>
      (super.noSuchMethod(
            Invocation.getter(#introductionFormLastPage),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get signUpLoginPage =>
      (super.noSuchMethod(
            Invocation.getter(#signUpLoginPage),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get personalInformationForm =>
      (super.noSuchMethod(
            Invocation.getter(#personalInformationForm),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, List<String>> get homePageInspirationalQuotes =>
      (super.noSuchMethod(
            Invocation.getter(#homePageInspirationalQuotes),
            returnValue: <String, List<String>>{},
            returnValueForMissingStub: <String, List<String>>{},
          )
          as Map<String, List<String>>);

  @override
  Map<String, String> get shareMessages =>
      (super.noSuchMethod(
            Invocation.getter(#shareMessages),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get sharePDFtexts =>
      (super.noSuchMethod(
            Invocation.getter(#sharePDFtexts),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  List<String> get thanksSuggestionsList =>
      (super.noSuchMethod(
            Invocation.getter(#thanksSuggestionsList),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> get phonePersonalPlanText =>
      (super.noSuchMethod(
            Invocation.getter(#phonePersonalPlanText),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  Map<String, String> get extraMenuStrings =>
      (super.noSuchMethod(
            Invocation.getter(#extraMenuStrings),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, List<String>> get positiveTraitsSuggestionsList =>
      (super.noSuchMethod(
            Invocation.getter(#positiveTraitsSuggestionsList),
            returnValue: <String, List<String>>{},
            returnValueForMissingStub: <String, List<String>>{},
          )
          as Map<String, List<String>>);

  @override
  Map<String, String> get formPhonePage =>
      (super.noSuchMethod(
            Invocation.getter(#formPhonePage),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, List<String>> get phonePageTitles =>
      (super.noSuchMethod(
            Invocation.getter(#phonePageTitles),
            returnValue: <String, List<String>>{},
            returnValueForMissingStub: <String, List<String>>{},
          )
          as Map<String, List<String>>);

  @override
  Map<String, String> get formDifficultEventsTitles =>
      (super.noSuchMethod(
            Invocation.getter(#formDifficultEventsTitles),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get formDistractionsTitles =>
      (super.noSuchMethod(
            Invocation.getter(#formDistractionsTitles),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get formFeelBetterTitles =>
      (super.noSuchMethod(
            Invocation.getter(#formFeelBetterTitles),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get formMakeSaferTitles =>
      (super.noSuchMethod(
            Invocation.getter(#formMakeSaferTitles),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get formSharePageTitles =>
      (super.noSuchMethod(
            Invocation.getter(#formSharePageTitles),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get formSkipButtonText =>
      (super.noSuchMethod(
            Invocation.getter(#formSkipButtonText),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get feelGoodPageTitles =>
      (super.noSuchMethod(
            Invocation.getter(#feelGoodPageTitles),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get syncPages =>
      (super.noSuchMethod(
            Invocation.getter(#syncPages),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  List<String> get test1 =>
      (super.noSuchMethod(
            Invocation.getter(#test1),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  String get appVersion =>
      (super.noSuchMethod(
            Invocation.getter(#appVersion),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#appVersion),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#appVersion),
            ),
          )
          as String);

  @override
  List<String> get DifficultEventsSug =>
      (super.noSuchMethod(
            Invocation.getter(#DifficultEventsSug),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> get DistractionsSug =>
      (super.noSuchMethod(
            Invocation.getter(#DistractionsSug),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> get FeelBetterSug =>
      (super.noSuchMethod(
            Invocation.getter(#FeelBetterSug),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<String> get MakeSaferSug =>
      (super.noSuchMethod(
            Invocation.getter(#MakeSaferSug),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  Map<String, String> get addFormStrings =>
      (super.noSuchMethod(
            Invocation.getter(#addFormStrings),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get addThanksFormStrings =>
      (super.noSuchMethod(
            Invocation.getter(#addThanksFormStrings),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get addFormPageTemplateStrings =>
      (super.noSuchMethod(
            Invocation.getter(#addFormPageTemplateStrings),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get IntroductionRestart =>
      (super.noSuchMethod(
            Invocation.getter(#IntroductionRestart),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, List<String>> get wellnessVideos =>
      (super.noSuchMethod(
            Invocation.getter(#wellnessVideos),
            returnValue: <String, List<String>>{},
            returnValueForMissingStub: <String, List<String>>{},
          )
          as Map<String, List<String>>);

  @override
  set disclaimerText(String? value) => super.noSuchMethod(
    Invocation.setter(#disclaimerText, value),
    returnValueForMissingStub: null,
  );

  @override
  set disclaimerNext(String? value) => super.noSuchMethod(
    Invocation.setter(#disclaimerNext, value),
    returnValueForMissingStub: null,
  );

  @override
  set reminderMainTitle(String? value) => super.noSuchMethod(
    Invocation.setter(#reminderMainTitle, value),
    returnValueForMissingStub: null,
  );

  @override
  set reminderSubTitle(String? value) => super.noSuchMethod(
    Invocation.setter(#reminderSubTitle, value),
    returnValueForMissingStub: null,
  );

  @override
  set homeTitleGreeting(String? value) => super.noSuchMethod(
    Invocation.setter(#homeTitleGreeting, value),
    returnValueForMissingStub: null,
  );

  @override
  set personalPlanMainTitle(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#personalPlanMainTitle, value),
    returnValueForMissingStub: null,
  );

  @override
  set personalPlanSubTitle(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#personalPlanSubTitle, value),
    returnValueForMissingStub: null,
  );

  @override
  set traitMainTitle(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#traitMainTitle, value),
    returnValueForMissingStub: null,
  );

  @override
  set traitSubTitle(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#traitSubTitle, value),
    returnValueForMissingStub: null,
  );

  @override
  set journalMainTitle(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#journalMainTitle, value),
    returnValueForMissingStub: null,
  );

  @override
  set journalSubTitle(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#journalSubTitle, value),
    returnValueForMissingStub: null,
  );

  @override
  set journalPopUpText(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#journalPopUpText, value),
    returnValueForMissingStub: null,
  );

  @override
  set positiveTraitsPopUpText(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#positiveTraitsPopUpText, value),
    returnValueForMissingStub: null,
  );

  @override
  set popupBack(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#popupBack, value),
    returnValueForMissingStub: null,
  );

  @override
  set othersuggestions(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#othersuggestions, value),
    returnValueForMissingStub: null,
  );

  @override
  set aboutPageText(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#aboutPageText, value),
    returnValueForMissingStub: null,
  );

  @override
  set returnToPlanStrings(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#returnToPlanStrings, value),
    returnValueForMissingStub: null,
  );

  @override
  set warningHomePageTitles(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#warningHomePageTitles, value),
    returnValueForMissingStub: null,
  );

  @override
  set traitsHomePageTitles(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#traitsHomePageTitles, value),
    returnValueForMissingStub: null,
  );

  @override
  set introductionFormFirstPage(Map<String, String>? value) =>
      super.noSuchMethod(
        Invocation.setter(#introductionFormFirstPage, value),
        returnValueForMissingStub: null,
      );

  @override
  set introductionFormSecondPage(Map<String, String>? value) =>
      super.noSuchMethod(
        Invocation.setter(#introductionFormSecondPage, value),
        returnValueForMissingStub: null,
      );

  @override
  set introductionFormLastPage(Map<String, String>? value) =>
      super.noSuchMethod(
        Invocation.setter(#introductionFormLastPage, value),
        returnValueForMissingStub: null,
      );

  @override
  set signUpLoginPage(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#signUpLoginPage, value),
    returnValueForMissingStub: null,
  );

  @override
  set personalInformationForm(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#personalInformationForm, value),
    returnValueForMissingStub: null,
  );

  @override
  set homePageInspirationalQuotes(Map<String, List<String>>? value) =>
      super.noSuchMethod(
        Invocation.setter(#homePageInspirationalQuotes, value),
        returnValueForMissingStub: null,
      );

  @override
  set shareMessages(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#shareMessages, value),
    returnValueForMissingStub: null,
  );

  @override
  set sharePDFtexts(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#sharePDFtexts, value),
    returnValueForMissingStub: null,
  );

  @override
  set thanksSuggestionsList(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#thanksSuggestionsList, value),
    returnValueForMissingStub: null,
  );

  @override
  set phonePersonalPlanText(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#phonePersonalPlanText, value),
    returnValueForMissingStub: null,
  );

  @override
  set extraMenuStrings(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#extraMenuStrings, value),
    returnValueForMissingStub: null,
  );

  @override
  set positiveTraitsSuggestionsList(Map<String, List<String>>? value) =>
      super.noSuchMethod(
        Invocation.setter(#positiveTraitsSuggestionsList, value),
        returnValueForMissingStub: null,
      );

  @override
  set formPhonePage(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#formPhonePage, value),
    returnValueForMissingStub: null,
  );

  @override
  set phonePageTitles(Map<String, List<String>>? value) => super.noSuchMethod(
    Invocation.setter(#phonePageTitles, value),
    returnValueForMissingStub: null,
  );

  @override
  set formDifficultEventsTitles(Map<String, String>? value) =>
      super.noSuchMethod(
        Invocation.setter(#formDifficultEventsTitles, value),
        returnValueForMissingStub: null,
      );

  @override
  set formDistractionsTitles(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#formDistractionsTitles, value),
    returnValueForMissingStub: null,
  );

  @override
  set formFeelBetterTitles(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#formFeelBetterTitles, value),
    returnValueForMissingStub: null,
  );

  @override
  set formMakeSaferTitles(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#formMakeSaferTitles, value),
    returnValueForMissingStub: null,
  );

  @override
  set formSharePageTitles(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#formSharePageTitles, value),
    returnValueForMissingStub: null,
  );

  @override
  set formSkipButtonText(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#formSkipButtonText, value),
    returnValueForMissingStub: null,
  );

  @override
  set feelGoodPageTitles(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#feelGoodPageTitles, value),
    returnValueForMissingStub: null,
  );

  @override
  set syncPages(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#syncPages, value),
    returnValueForMissingStub: null,
  );

  @override
  set test1(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#test1, value),
    returnValueForMissingStub: null,
  );

  @override
  set lastUpdated(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#lastUpdated, value),
    returnValueForMissingStub: null,
  );

  @override
  set appVersion(String? value) => super.noSuchMethod(
    Invocation.setter(#appVersion, value),
    returnValueForMissingStub: null,
  );

  @override
  set DifficultEventsSug(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#DifficultEventsSug, value),
    returnValueForMissingStub: null,
  );

  @override
  set DistractionsSug(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#DistractionsSug, value),
    returnValueForMissingStub: null,
  );

  @override
  set FeelBetterSug(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#FeelBetterSug, value),
    returnValueForMissingStub: null,
  );

  @override
  set MakeSaferSug(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#MakeSaferSug, value),
    returnValueForMissingStub: null,
  );

  @override
  set addFormStrings(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#addFormStrings, value),
    returnValueForMissingStub: null,
  );

  @override
  set addThanksFormStrings(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#addThanksFormStrings, value),
    returnValueForMissingStub: null,
  );

  @override
  set addFormPageTemplateStrings(Map<String, String>? value) =>
      super.noSuchMethod(
        Invocation.setter(#addFormPageTemplateStrings, value),
        returnValueForMissingStub: null,
      );

  @override
  set IntroductionRestart(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#IntroductionRestart, value),
    returnValueForMissingStub: null,
  );

  @override
  set wellnessVideos(Map<String, List<String>>? value) => super.noSuchMethod(
    Invocation.setter(#wellnessVideos, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void updateReminderMainTitle(String? title) => super.noSuchMethod(
    Invocation.method(#updateReminderMainTitle, [title]),
    returnValueForMissingStub: null,
  );

  @override
  void updateReminderSubTitle(String? subTitle) => super.noSuchMethod(
    Invocation.method(#updateReminderSubTitle, [subTitle]),
    returnValueForMissingStub: null,
  );

  @override
  void updateHomeTitleGreeting(String? greeting) => super.noSuchMethod(
    Invocation.method(#updateHomeTitleGreeting, [greeting]),
    returnValueForMissingStub: null,
  );

  @override
  void updatePersonalPlanMainTitle(Map<String, String>? title) =>
      super.noSuchMethod(
        Invocation.method(#updatePersonalPlanMainTitle, [title]),
        returnValueForMissingStub: null,
      );

  @override
  void updatePersonalPlanSubTitle(Map<String, String>? subTitle) =>
      super.noSuchMethod(
        Invocation.method(#updatePersonalPlanSubTitle, [subTitle]),
        returnValueForMissingStub: null,
      );

  @override
  void updateTraitMainTitle(Map<String, String>? title) => super.noSuchMethod(
    Invocation.method(#updateTraitMainTitle, [title]),
    returnValueForMissingStub: null,
  );

  @override
  void updateTraitSubTitle(Map<String, String>? subTitle) => super.noSuchMethod(
    Invocation.method(#updateTraitSubTitle, [subTitle]),
    returnValueForMissingStub: null,
  );

  @override
  void updateJournalMainTitle(Map<String, String>? title) => super.noSuchMethod(
    Invocation.method(#updateJournalMainTitle, [title]),
    returnValueForMissingStub: null,
  );

  @override
  void updateJournalSubTitle(Map<String, String>? subTitle) =>
      super.noSuchMethod(
        Invocation.method(#updateJournalSubTitle, [subTitle]),
        returnValueForMissingStub: null,
      );

  @override
  void updateReturnToPlanStrings(Map<String, String>? strings) =>
      super.noSuchMethod(
        Invocation.method(#updateReturnToPlanStrings, [strings]),
        returnValueForMissingStub: null,
      );

  @override
  void updateWarningHomePageTitles(Map<String, String>? titles) =>
      super.noSuchMethod(
        Invocation.method(#updateWarningHomePageTitles, [titles]),
        returnValueForMissingStub: null,
      );

  @override
  void updateTraitsHomePageTitles(Map<String, String>? titles) =>
      super.noSuchMethod(
        Invocation.method(#updateTraitsHomePageTitles, [titles]),
        returnValueForMissingStub: null,
      );

  @override
  void updateIntroductionFormFirstPage(Map<String, String>? form) =>
      super.noSuchMethod(
        Invocation.method(#updateIntroductionFormFirstPage, [form]),
        returnValueForMissingStub: null,
      );

  @override
  void updateIntroductionFormSecondPage(Map<String, String>? form) =>
      super.noSuchMethod(
        Invocation.method(#updateIntroductionFormSecondPage, [form]),
        returnValueForMissingStub: null,
      );

  @override
  void updateIntroductionFormLastPage(Map<String, String>? form) =>
      super.noSuchMethod(
        Invocation.method(#updateIntroductionFormLastPage, [form]),
        returnValueForMissingStub: null,
      );

  @override
  void updatePersonalInformationForm(Map<String, String>? form) =>
      super.noSuchMethod(
        Invocation.method(#updatePersonalInformationForm, [form]),
        returnValueForMissingStub: null,
      );

  @override
  void updateLastUpdated(DateTime? date) => super.noSuchMethod(
    Invocation.method(#updateLastUpdated, [date]),
    returnValueForMissingStub: null,
  );

  @override
  void updateHomePageInspirationalQuotes(Map<String, List<String>>? quotes) =>
      super.noSuchMethod(
        Invocation.method(#updateHomePageInspirationalQuotes, [quotes]),
        returnValueForMissingStub: null,
      );

  @override
  void updateTest1(List<String>? test) => super.noSuchMethod(
    Invocation.method(#updateTest1, [test]),
    returnValueForMissingStub: null,
  );

  @override
  void updateShareMessages(Map<String, String>? messages) => super.noSuchMethod(
    Invocation.method(#updateShareMessages, [messages]),
    returnValueForMissingStub: null,
  );

  @override
  void updateThanksSuggestionsList(List<String>? suggestions) =>
      super.noSuchMethod(
        Invocation.method(#updateThanksSuggestionsList, [suggestions]),
        returnValueForMissingStub: null,
      );

  @override
  void updatePositiveTraitsSuggestionsList(
    Map<String, List<String>>? suggestions,
  ) => super.noSuchMethod(
    Invocation.method(#updatePositiveTraitsSuggestionsList, [suggestions]),
    returnValueForMissingStub: null,
  );

  @override
  void updateJournalPopUpText(Map<String, String>? text) => super.noSuchMethod(
    Invocation.method(#updateJournalPopUpText, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void updatePositiveTraitsPopUpText(Map<String, String>? text) =>
      super.noSuchMethod(
        Invocation.method(#updatePositiveTraitsPopUpText, [text]),
        returnValueForMissingStub: null,
      );

  @override
  void updateFormPhonePage(Map<String, String>? form) => super.noSuchMethod(
    Invocation.method(#updateFormPhonePage, [form]),
    returnValueForMissingStub: null,
  );

  @override
  void updatePhonePageTitles(Map<String, List<String>>? titles) =>
      super.noSuchMethod(
        Invocation.method(#updatePhonePageTitles, [titles]),
        returnValueForMissingStub: null,
      );

  @override
  void updateFormDifficultEventsTitles(Map<String, String>? titles) =>
      super.noSuchMethod(
        Invocation.method(#updateFormDifficultEventsTitles, [titles]),
        returnValueForMissingStub: null,
      );

  @override
  void updateFormDistractionsTitles(Map<String, String>? titles) =>
      super.noSuchMethod(
        Invocation.method(#updateFormDistractionsTitles, [titles]),
        returnValueForMissingStub: null,
      );

  @override
  void updateFormFeelBetterTitles(Map<String, String>? titles) =>
      super.noSuchMethod(
        Invocation.method(#updateFormFeelBetterTitles, [titles]),
        returnValueForMissingStub: null,
      );

  @override
  void updateFormMakeSaferTitles(Map<String, String>? titles) =>
      super.noSuchMethod(
        Invocation.method(#updateFormMakeSaferTitles, [titles]),
        returnValueForMissingStub: null,
      );

  @override
  void updateFormSharePageTitles(Map<String, String>? titles) =>
      super.noSuchMethod(
        Invocation.method(#updateFormSharePageTitles, [titles]),
        returnValueForMissingStub: null,
      );

  @override
  void updatePhonePersonalPlanText(dynamic texts) => super.noSuchMethod(
    Invocation.method(#updatePhonePersonalPlanText, [texts]),
    returnValueForMissingStub: null,
  );

  @override
  void updateAppVersion(String? version) => super.noSuchMethod(
    Invocation.method(#updateAppVersion, [version]),
    returnValueForMissingStub: null,
  );

  @override
  void updateDifficultEventsSug(List<String>? sug) => super.noSuchMethod(
    Invocation.method(#updateDifficultEventsSug, [sug]),
    returnValueForMissingStub: null,
  );

  @override
  void updateDistractionsSug(List<String>? sug) => super.noSuchMethod(
    Invocation.method(#updateDistractionsSug, [sug]),
    returnValueForMissingStub: null,
  );

  @override
  void updateFeelBetterSug(List<String>? sug) => super.noSuchMethod(
    Invocation.method(#updateFeelBetterSug, [sug]),
    returnValueForMissingStub: null,
  );

  @override
  void updateMakeSaferSug(List<String>? sug) => super.noSuchMethod(
    Invocation.method(#updateMakeSaferSug, [sug]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSharePDFtexts(Map<String, String>? texts) => super.noSuchMethod(
    Invocation.method(#updateSharePDFtexts, [texts]),
    returnValueForMissingStub: null,
  );

  @override
  void updateWellnessVideos(Map<String, List<String>>? videos) =>
      super.noSuchMethod(
        Invocation.method(#updateWellnessVideos, [videos]),
        returnValueForMissingStub: null,
      );

  @override
  void updateAboutPageText(Map<String, String>? texts) => super.noSuchMethod(
    Invocation.method(#updateAboutPageText, [texts]),
    returnValueForMissingStub: null,
  );

  @override
  void updateDisclaimerPageText(String? text) => super.noSuchMethod(
    Invocation.method(#updateDisclaimerPageText, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void updateDisclaimerPageNext(String? text) => super.noSuchMethod(
    Invocation.method(#updateDisclaimerPageNext, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void updateFormSkipButtonText(Map<String, String>? text) =>
      super.noSuchMethod(
        Invocation.method(#updateFormSkipButtonText, [text]),
        returnValueForMissingStub: null,
      );

  @override
  void updateFeelGoodPageTitles(Map<String, String>? text) =>
      super.noSuchMethod(
        Invocation.method(#updateFeelGoodPageTitles, [text]),
        returnValueForMissingStub: null,
      );

  @override
  void updateExtraMenuStrings(Map<String, String>? text) => super.noSuchMethod(
    Invocation.method(#updateExtraMenuStrings, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSyncPages(Map<String, String>? text) => super.noSuchMethod(
    Invocation.method(#updateSyncPages, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void updatePopupBack(Map<String, String>? text) => super.noSuchMethod(
    Invocation.method(#updatePopupBack, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSignUpLoginPage(Map<String, String>? text) => super.noSuchMethod(
    Invocation.method(#updateSignUpLoginPage, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void updateAddFormStrings(Map<String, String>? text) => super.noSuchMethod(
    Invocation.method(#updateAddFormStrings, [text]),
    returnValueForMissingStub: null,
  );

  @override
  void updateAddThanksFormStrings(Map<String, String>? text) =>
      super.noSuchMethod(
        Invocation.method(#updateAddThanksFormStrings, [text]),
        returnValueForMissingStub: null,
      );

  @override
  void updateAddFormPageTemplateStrings(Map<String, String>? text) =>
      super.noSuchMethod(
        Invocation.method(#updateAddFormPageTemplateStrings, [text]),
        returnValueForMissingStub: null,
      );

  @override
  void updateIntroductionRestart(Map<String, String>? text) =>
      super.noSuchMethod(
        Invocation.method(#updateIntroductionRestart, [text]),
        returnValueForMissingStub: null,
      );

  @override
  void updateOtherSuggestions(Map<String, String>? title) => super.noSuchMethod(
    Invocation.method(#updateOtherSuggestions, [title]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i16.SharedPreferences {
  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValueForMissingStub: null,
          )
          as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValueForMissingStub: null,
          )
          as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key]),
            returnValueForMissingStub: null,
          )
          as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValueForMissingStub: null,
          )
          as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getStringList, [key]),
            returnValueForMissingStub: null,
          )
          as List<String>?);

  @override
  _i7.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [VideoPlayerPageFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoPlayerPageFactory extends _i1.Mock
    implements _i17.VideoPlayerPageFactory {
  @override
  _i3.Widget create({
    required dynamic Function(bool)? onFullScreenChanged,
    required Map<String, List<String>>? videoData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #onFullScreenChanged: onFullScreenChanged,
              #videoData: videoData,
            }),
            returnValue: _FakeWidget_1(
              this,
              Invocation.method(#create, [], {
                #onFullScreenChanged: onFullScreenChanged,
                #videoData: videoData,
              }),
            ),
            returnValueForMissingStub: _FakeWidget_1(
              this,
              Invocation.method(#create, [], {
                #onFullScreenChanged: onFullScreenChanged,
                #videoData: videoData,
              }),
            ),
          )
          as _i3.Widget);
}

/// A class which mocks [ImagePickerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePickerService extends _i1.Mock
    implements _i18.ImagePickerService {
  @override
  _i7.Future<_i8.XFile?> pickImage({required _i19.ImageSource? source}) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [], {#source: source}),
            returnValue: _i7.Future<_i8.XFile?>.value(),
            returnValueForMissingStub: _i7.Future<_i8.XFile?>.value(),
          )
          as _i7.Future<_i8.XFile?>);

  @override
  _i7.Future<_i5.File> saveImagePaths(List<String>? imagePaths) =>
      (super.noSuchMethod(
            Invocation.method(#saveImagePaths, [imagePaths]),
            returnValue: _i7.Future<_i5.File>.value(
              _FakeFile_2(
                this,
                Invocation.method(#saveImagePaths, [imagePaths]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.File>.value(
              _FakeFile_2(
                this,
                Invocation.method(#saveImagePaths, [imagePaths]),
              ),
            ),
          )
          as _i7.Future<_i5.File>);

  @override
  _i7.Future<void> getImage(String? source, List<String>? imagePaths) =>
      (super.noSuchMethod(
            Invocation.method(#getImage, [source, imagePaths]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void deleteImage(int? index, List<String>? imagePaths) => super.noSuchMethod(
    Invocation.method(#deleteImage, [index, imagePaths]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> loadImagePaths(List<String>? imagePaths) =>
      (super.noSuchMethod(
            Invocation.method(#loadImagePaths, [imagePaths]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i3.Widget displayImage(String? path, {_i3.BoxFit? fit = _i3.BoxFit.none}) =>
      (super.noSuchMethod(
            Invocation.method(#displayImage, [path], {#fit: fit}),
            returnValue: _FakeWidget_1(
              this,
              Invocation.method(#displayImage, [path], {#fit: fit}),
            ),
            returnValueForMissingStub: _FakeWidget_1(
              this,
              Invocation.method(#displayImage, [path], {#fit: fit}),
            ),
          )
          as _i3.Widget);

  @override
  _i3.Widget getOnlineImage(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getOnlineImage, [url]),
            returnValue: _FakeWidget_1(
              this,
              Invocation.method(#getOnlineImage, [url]),
            ),
            returnValueForMissingStub: _FakeWidget_1(
              this,
              Invocation.method(#getOnlineImage, [url]),
            ),
          )
          as _i3.Widget);

  @override
  _i7.Future<void> deleteImages() =>
      (super.noSuchMethod(
            Invocation.method(#deleteImages, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> downloadImage(
    String? imagePath, {
    String? fileName,
    String? dialogTitle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadImage,
              [imagePath],
              {#fileName: fileName, #dialogTitle: dialogTitle},
            ),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<Map<String, int>> loadImageRotations() =>
      (super.noSuchMethod(
            Invocation.method(#loadImageRotations, []),
            returnValue: _i7.Future<Map<String, int>>.value(<String, int>{}),
            returnValueForMissingStub: _i7.Future<Map<String, int>>.value(
              <String, int>{},
            ),
          )
          as _i7.Future<Map<String, int>>);

  @override
  _i7.Future<void> saveImageRotations(Map<String, int>? imageRotations) =>
      (super.noSuchMethod(
            Invocation.method(#saveImageRotations, [imageRotations]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i20.AnalyticsService {
  @override
  _i7.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> trackEvent(
    String? eventName, [
    Map<String, dynamic>? properties,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#trackEvent, [eventName, properties]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [PersistentMemoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistentMemoryService extends _i1.Mock
    implements _i2.PersistentMemoryService {
  @override
  _i7.Future<void> setItem(
    String? key,
    _i9.PersistentMemoryType? type,
    dynamic value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setItem, [key, type, value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<dynamic> getItem(String? key, _i9.PersistentMemoryType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getItem, [key, type]),
            returnValue: _i7.Future<dynamic>.value(),
            returnValueForMissingStub: _i7.Future<dynamic>.value(),
          )
          as _i7.Future<dynamic>);

  @override
  _i7.Future<Map<String, Object?>> readSnapshot(
    Map<String, _i9.PersistentMemoryType>? keys,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readSnapshot, [keys]),
            returnValue: _i7.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
            returnValueForMissingStub: _i7.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i7.Future<Map<String, Object?>>);

  @override
  _i7.Future<void> reset() =>
      (super.noSuchMethod(
            Invocation.method(#reset, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
